# Generated by Django 6.0.4 on 2026-04-28 14:05

import django.db.models.deletion
import employees.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200)),
                ('job_title', models.CharField(max_length=200)),
                ('employee_id', models.CharField(blank=True, db_index=True, max_length=32, unique=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to=employees.models.employee_photo_upload_to)),
                ('qr_code', models.ImageField(blank=True, editable=False, null=True, upload_to=employees.models.employee_qr_upload_to)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='employees', to='employees.department')),
            ],
            options={
                'ordering': ['full_name'],
            },
        ),
    ]
